services:
  app:
    image: "ghcr.io/sandrodegiorgi/rbs-openai-simple-docker/rbs-openai-simple-docker:latest"
    container_name: rbs-openai
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PASSWORD=${PASSWORD}
    restart: unless-stopped
    pull_policy: always
    volumes:
      - /opt/docker/data/rbs-openai/images:/app/images
      - /opt/docker/data/rbs-openai/assistants:/app/assistants
    networks:
      - proxy

networks:
  proxy:
    external: true
