services:
  app:
    image: "ghcr.io/sandrodegiorgi/rbs-openai-simple-docker/rbs-openai-simple-docker:latest"
    container_name: rbs-openai
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PASSWORD=${PASSWORD}
      - PASSWORD_CHAT=${PASSWORD_CHAT}
      - PASSWORD_IMAGE=${PASSWORD_IMAGE}
      - PASSWORD_TRANSLATE=${PASSWORD_TRANSLATE}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    restart: unless-stopped
    pull_policy: always
    volumes:
      - /opt/docker/data/rbs-openai/images:/app/images
      - /opt/docker/data/rbs-openai/assistants:/app/assistants
    networks:
      - proxy

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: rbs-ai
    ports:
      - "3306:3306"
    volumes:
      - /opt/docker/data/rbs-openai/db:/var/lib/mysql
#       - /opt/docker/data/Useris/sandrodegiorgi/Documents/mariadb/data:/var/lib/mysql
    networks:
      - proxy

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    # restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

networks:
  proxy:
    external: true
